Repository elastic/apm-aws-lambda, pull requests merged in 2022-10, with the labels that each got.

#324 Log a message if capture logs env var is malformed
  main.go
Labels: aws-λ-extension

#327 docs: fix layout in new book
  docs/monitoring-aws-lambda.asciidoc
Labels: documentation, Team:Docs, aws-λ-extension

#329 ci: add smoke testing job definition
  .ci/jobs/apm-aws-lambda-smoketests-mbp.yml
Labels: aws-λ-extension

#328 docs: add release notes to docs
  .gitignore
  docs/index.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Docs, aws-λ-extension

#314 Batch lambda logs API data before sending to APM-Server
  CHANGELOG.asciidoc
  apmproxy/apmserver.go
  apmproxy/apmserver_test.go
  apmproxy/batch.go
  apmproxy/batch_test.go
  apmproxy/client.go
  apmproxy/client_test.go
  apmproxy/metadata.go
  apmproxy/metadata_test.go
  apmproxy/option.go
  apmproxy/receiver.go
  apmproxy/receiver_test.go
  app/run.go
  logsapi/event.go
  logsapi/functionlogs.go
  logsapi/functionlogs_test.go
  logsapi/metrics.go
  logsapi/metrics_test.go
  logsapi/route_handlers.go
  logsapi/subscribe.go
  main_test.go
Labels: aws-λ-extension

#336 Remove usage of APMData within logsapi
  apmproxy/apmserver.go
  apmproxy/apmserver_test.go
  apmproxy/batch.go
  apmproxy/batch_test.go
  apmproxy/client.go
  app/run.go
  logsapi/event.go
  logsapi/functionlogs.go
  logsapi/functionlogs_test.go
  logsapi/metrics.go
  logsapi/metrics_test.go
Labels: aws-λ-extension

#331 release: delete layer before publishing
  .ci/Jenkinsfile
  Makefile
Labels: Team:Automation, aws-λ-extension
