Repository elastic/apm-aws-lambda, pull requests merged in 2023-01, with the labels that each got.

#356 build: update notice to 2023
  NOTICE.txt
Labels: aws-λ-extension

#355 build: Tag CSP resources according to policy
  testing/benchmarking/main.tf
  tf/main.tf
  tf/variables.tf
Labels: aws-λ-extension

#358 Process platform report metrics when extn is lagging
  CHANGELOG.asciidoc
  accumulator/batch.go
  accumulator/invocation.go
  accumulator/invocation_test.go
  app/run.go
  logsapi/client.go
  logsapi/event.go
  logsapi/metrics.go
  logsapi/metrics_test.go
Labels: aws-λ-extension

#359 build: strip debugging information from final binary
  Makefile
Labels: aws-λ-extension

#357 Add TLS support (#186)
  NOTICE.txt
  apmproxy/option.go
  apmproxy/receiver.go
  apmproxy/receiver_test.go
  app/app.go
  app/aws.go
  dependencies.asciidoc
  go.mod
  go.sum
Labels: aws-λ-extension, community, triage

#363 test: use 127.0.0.1 explicitly instead of resolving localhost
  apmproxy/receiver_test.go
Labels: aws-λ-extension

#365 docs: update lambda config
  docs/monitoring-aws-lambda.asciidoc
Labels: Team:Docs, aws-λ-extension

#369 [8.6] docs: update lambda config (#365)
  docs/monitoring-aws-lambda.asciidoc
Labels: aws-λ-extension

#366 ci: fix gh status check
  .ci/jobs/apm-aws-lambda-smoketests-mbp.yml
Labels: Team:Automation
